# Generated by Django 3.1.4 on 2021-01-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201229_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='langauge',
            new_name='language',
        ),
    ]
